name: MSBuild

on:
  push:
    branches: [ main, stable/* ]
  pull_request:
    branches: [ main, stable/* ]
  workflow_dispatch:

env:
  SOLUTION_FILE_PATH: build/src/AnkhSVN.sln

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Git Checkout
      uses: actions/checkout@v6
      with:
        path: build

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Add Subversion to PATH
      uses: ampscm/setup-subversion@v1

    - name: Add VSTest to PATH
      run: |
        $vsPath = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -property installationPath
        $vstestPath = Join-Path $vsPath "Common7\IDE\CommonExtensions\Microsoft\TestWindow"
        Add-Content -Path $env:GITHUB_PATH -Value $vstestPath
      shell: powershell

    - name: Setup version
      working-directory: build
      run: cmd.exe /C scripts\gh-version-setup ${{ github.run_number }}

    - name: Build 2026
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /v:m /restore /t:rebuild /p:UseVsSdkVersion=18.0 /p:Configuration=Release ${{env.SOLUTION_FILE_PATH}} @build\scripts\msbuild-version.rsp

    - name: Package vsix 2026
      uses: actions/upload-artifact@v6
      with:
        name: Ankh-VSIX-2026
        path: build/src/Ankh.Package/bin/release/Ankh.Package.vsix
